/** IPC 通道名集中定义，避免主进程与 preload 之间字符串散落 */
export const IpcChannels = {
  GetDefaultRootDir: 'devzen:getDefaultRootDir',
  PickRootDir: 'devzen:pickRootDir',
  ScanProjects: 'devzen:scanProjects',
  ScanProgress: 'devzen:scanProgress',
  CleanDirs: 'devzen:cleanDirs',
  RevealInFinder: 'devzen:revealInFinder',
  CheckProjectDirty: 'devzen:checkProjectDirty',
  ArchiveProject: 'devzen:archiveProject',
  ListArchives: 'devzen:listArchives',
  RestoreProject: 'devzen:restoreProject',
  ForgetArchive: 'devzen:forgetArchive',
  GetProjectDetail: 'devzen:getProjectDetail',
  RefreshProjectDirty: 'devzen:refreshProjectDirty',
  OpenWithEditor: 'devzen:openWithEditor',
  OpenWithTerminal: 'devzen:openWithTerminal',
  ListHistory: 'devzen:listHistory',
  UpsertHistory: 'devzen:upsertHistory',
  RemoveHistory: 'devzen:removeHistory',
  BulkMergeHistory: 'devzen:bulkMergeHistory',
  // 冷备包（bundle）
  GetSettings: 'devzen:getSettings',
  SetBackupDir: 'devzen:setBackupDir',
  PickBackupDir: 'devzen:pickBackupDir',
  PickDir: 'devzen:pickDir',
  BundleArchive: 'devzen:bundleArchive',
  BundleAndRemove: 'devzen:bundleAndRemove',
  ListBundles: 'devzen:listBundles',
  VerifyBundle: 'devzen:verifyBundle',
  RestoreBundle: 'devzen:restoreBundle',
  DeleteBundle: 'devzen:deleteBundle',
  BundleProgress: 'devzen:bundleProgress',
  /** 打开应用使用说明（GitHub 上的 docs/使用说明.md） */
  OpenHelp: 'devzen:openHelp'
} as const;
